[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/Patient-dashboard/Yourappointments"
  to = "/Patient-dashboard/Yourappointments/"
  status = 200

[[redirects]]
  from = "/Doctor-dashboard"
  to = "/Doctor-dashboard/"
  status = 200

# API proxies
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200