[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_test_Ymxlc3NlZC1kb2Jlcm1hbi0xLmNsZXJrLmFjY291bnRzLmRldiQ"
  CLERK_SECRET_KEY = "sk_test_kr5d2Xmkz28XRNVoMQeDBrXGD24gTGrlZwukdlrbGY"
  NEXT_PUBLIC_SUPABASE_URL = "https://aytivtjsnrculxggyfzn.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5dGl2dGpzbnJjdWx4Z2d5ZnpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNDY5ODYsImV4cCI6MjA3MjgyMjk4Nn0.mFz2e2wewz_6oPWxZWg-My--S4OrgWttavQHCWwPJ54"
  SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5dGl2dGpzbnJjdWx4Z2d5ZnpuIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NzI0Njk4NiwiZXhwIjoyMDcyODIyOTg2fQ.k5bduGYbDbb4zc3BPo5mjGUYar4wA-Siz29rCWcH2ZQ"
  CLERK_WEBHOOK_SECRET = "whsec_pM2Xqse9QnDvbb/665eoJx5VG/PARBtl"
  CLERK_PUBLISHABLE_KEY = "pk_test_Ymxlc3NlZC1kb2Jlcm1hbi0xLmNsZXJrLmFjY291bnRzLmRldiQ"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200