  // lib/constants.js
export const PLAN_CREDITS = {
  free_user: 2,
  standard: 10,
  premium: 24,
};

export const APPOINTMENT_CREDIT_COST = 2;

export const USER_ROLES = {
  PATIENT: 'PATIENT',
  DOCTOR: 'DOCTOR',
  ADMIN: 'ADMIN',
  UNASSIGNED: 'UNASSIGNED'
};

export const VERIFICATION_STATUS = {
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED'
};

export const TRANSACTION_TYPES = {
  CREDIT_PURCHASE: 'CREDIT_PURCHASE',
  APPOINTMENT_DEDUCTION: 'APPOINTMENT_DEDUCTION',
  APPOINTMENT_EARNING: 'APPOINTMENT_EARNING',
  ADMIN_ADJUSTMENT: 'ADMIN_ADJUSTMENT',
  SUBSCRIPTION_CREDIT: 'SUBSCRIPTION_CREDIT'
};
